version: "3.9"
services:
  rails_app:
    build: rails_app/
    ports:
      - "3000:3000"
    environment:
      MINECRAFT_SERVICE_NAME: "minecraft"
      MINECRAFT_STATUS_PORT: 25566
      RAILS_ENV: ${RAILS_ENV}
      ANDRE_GMAIL_USERNAME: ${ANDRE_GMAIL_USERNAME}
      ANDRE_GMAIL_PASSWORD: ${ANDRE_GMAIL_PASSWORD}
    volumes:
      - rails-db:/root/rails_app/db
  minecraft:
    build: minecraft/
    environment:
      MINECRAFT_STARTUP_COMMAND: ${MINECRAFT_STARTUP_COMMAND}
      MINECRAFT_STATUS_PORT: 25566
      SPIGOT_HOST_NAME: ${SPIGOT_HOST_NAME}
      SPIGOT_PORT: ${SPIGOT_PORT}
    ports:
      - "25565:25565"
      - "25566:25566"
    volumes:
      - minecraft-data:/root/minecraft
volumes:
  minecraft-data:
    name: minecraft-data
  rails-db:
    name: rails-db
