version: "3.9"
services:
  rails_app:
    build: rails_app/
    ports:
      - "80:80"
    environment:
      RUBY_VERSION: "3.0.2"
      MINECRAFT_SERVICE_NAME: "minecraft"
      MINECRAFT_STATUS_PORT: 25566
      RAILS_ENV: "development"
  minecraft:
    build: minecraft/
    environment:
      MINECRAFT_STARTUP_COMMAND: "screen -dmS minecraft java -jar /root/minecraft/minecraft-server.jar"
      MINECRAFT_STATUS_PORT: 25566
      SPIGOT_HOST_NAME: "localhost"
      SPIGOT_PORT: "25567"
    ports:
      - "25565:25565"
      - "25566:25566"
    volumes:
      - minecraft-data:/root/minecraft
volumes:
  minecraft-data:
    external: true
    name: minecraft-data
