version: "3.9"
services:
  rails_app:
    build: rails_app/
    ports:
      - "3000:3000"
    environment:
      MINECRAFT_SERVICE_NAME: "minecraft"
      MINECRAFT_STATUS_PORT: 25566
      RAILS_ENV: "development"
    volumes:
      - rails-db:/root/rails_app/db
  minecraft:
    build: minecraft/
    environment:
      MINECRAFT_STARTUP_COMMAND: "screen -dmS minecraft java -jar /root/minecraft/minecraft-server.jar"
      MINECRAFT_STATUS_PORT: 25566
      SPIGOT_HOST_NAME: "localhost"
      SPIGOT_PORT: 25567
    ports:
      - "25565:25565"
      - "25566:25566"
    volumes:
      - minecraft-data:/root/minecraft
volumes:
  minecraft-data:
    name: minecraft-data
  rails-db:
    name: rails-db
