module SpigotInterface
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  
  class SpigotConnection
    def initialize: () -> void
    def start: () -> String
    def stop: () -> String
    def notify: () -> String
    def status: () -> String
    def players: () -> String
  end
end
