FROM eclipse-temurin:17

SHELL ["/bin/bash", "-c"]
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt update
RUN apt install -y wget git

RUN mkdir /tmp/build_spigot
WORKDIR /tmp/build_spigot
RUN wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
RUN java -jar BuildTools.jar

RUN mv spigot**.jar minecraft_server.jar
RUN mkdir /root/minecraft
RUN mv minecraft_server.jar /root/minecraft
WORKDIR /root/minecraft
